[package]
name = "execution"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "execution"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
